bool es_btn                     # if True, error is set on emergency buttons set 1
bool zone_safe                  # if True, error is set on zone safe detection
bool os3_error_rear             # if True, error is set on OS3 rear (error in sensor)
bool os3_error_front            # if True, error is set on OS3 front (error in sensor)
bool os3_warn_rear              # if True, warning field of OS3 rear is set
bool os3_warn_front             # if True, warning field of OS3 front is set
bool os3_protect_rear           # if True, protection field OS3 rear is set
bool os3_protect_front          # if True, protection field OS3 front is set
bool baumer                     # if True, error is set in baumer sensor
bool es_btn_2                   # if True, error is set on emergency buttons set 2
bool shovel_position            # if True, shovel is not at the good place to drive
bool heartbeat                  # if True, heartbeat is missing
